name: Build and Deploy to Koyeb

on:
  push:
    branches:
      - prod # Change if using another branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set environment variables
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image with specific tag
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tc-service-user-manage:${{ env.IMAGE_TAG }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/tc-service-user-manage:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/tc-service-user-manage:latest

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/tc-service-user-manage:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/tc-service-user-manage:latest

      - name: Deploy to Koyeb
        run: |
          echo "Deploying to Koyeb..."
          SERVICE_JSON=$(curl -# -X PATCH "https://app.koyeb.com/v1/services/${{ secrets.KOYEB_SERVICE_ID }}" \
            -H "Authorization: Bearer ${{ secrets.KOYEB_API_KEY }}" \
            -H "Content-Type: application/json" \
            -d '{ "definition": ${{ secrets.KOYEB_SERVICE_DEFINITION }} }')

          echo "Deployment response received. Extracting relevant details..."
          echo "$SERVICE_JSON" | jq '{id: .service.id, created_at: .service.created_at, updated_at: .service.updated_at, started_at: .service.started_at, succeeded_at: .service.succeeded_at, paused_at: .service.paused_at, resumed_at: .service.resumed_at, terminated_at: .service.terminated_at, name: .service.name, status: .service.status, messages: .service.messages, version: .service.version}'
