name: Deploy to Vercel

on:
  push:
	branches: [prod]

jobs:
  deploy:
	runs-on: ubuntu-latest
	if: contains(github.ref, 'refs/heads/prod')
	steps:
  	- name: Checkout code
    	uses: actions/checkout@v3

  	- name: Set up Node.js
    	uses: actions/setup-node@v3
    	with:
      	node-version: "22" # Specify the Node.js version to use

  	- name: Install dependencies
    	run: npm install

  	- name: Build project
    	run: npm run build

  	- name: Setup Environment variables (Prod)
    	run: |
      	echo "NODE_ENV=${{ env.BRANCH_NAME }}" >> $GITHUB_ENV
      	echo "VERCEL_PROJECT_ID=${{ secrets.VERCEL_PROJECT_ID_PROD }}" >> $GITHUB_ENV
      	echo "VERCEL_ORG_ID=${{ secrets.VERCEL_ORG_ID_PROD }}" >> $GITHUB_ENV

  	- name: Deploy to Vercel (Prod)
    	if: ${{ github.ref == 'refs/heads/prod' }}
    	uses: amondnet/vercel-action@v20
    	with:
      	vercel-token: ${{ secrets.VERCEL_TOKEN }}
      	vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_PROD }}
      	vercel-org-id: ${{ secrets.VERCEL_ORG_ID_PROD }}
      	vercel-args: "--prod"
    	env:
      	VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
