name: Build and Deploy to Render

on:
  push:
    branches:
      - prod # Change if using another branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set environment variables
        run: echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build Docker image with specific tag
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/tc-service-user-manage:${{ env.IMAGE_TAG }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/tc-service-user-manage:${{ env.IMAGE_TAG }} ${{ secrets.DOCKER_USERNAME }}/tc-service-user-manage:latest

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/tc-service-user-manage:${{ env.IMAGE_TAG }}
          docker push ${{ secrets.DOCKER_USERNAME }}/tc-service-user-manage:latest

      - name: Trigger Render Deploy Hook
        run: |
          echo "Deploying to Render..."
          curl -# -X POST "$DEPLOY_HOOK_URL"
        env:
          DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK }}
